spring.application.name=dns
spring.datasource.url=jdbc:postgresql://localhost:5432/dns
spring.datasource.username=dns
spring.datasource.password=dns
spring.jpa.hibernate.ddl-auto=create
vaadin.features.badgeComponent=true
